Repository Davidyz/VectorCode, pull requests merged in 2025-07, with the labels that each got.

#232 Implement wildcard tool opts for CodeCompanion
  lua/codecompanion/_extensions/vectorcode/init.lua
  lua/vectorcode/integrations/codecompanion/common.lua
  lua/vectorcode/integrations/codecompanion/files_ls_tool.lua
  lua/vectorcode/integrations/codecompanion/files_rm_tool.lua
  lua/vectorcode/integrations/codecompanion/ls_tool.lua
  lua/vectorcode/integrations/codecompanion/query_tool.lua
  lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
Labels: enhancement, feature

#235 Add `files_ls` and `files_rm` tools to MCP server
  doc/VectorCode-cli.txt
  docs/cli.md
  src/vectorcode/mcp_main.py
  tests/test_mcp.py
Labels: enhancement, feature

#233 Readme updates
  README.md
  doc/VectorCode.txt
  docs/neovim.md
Labels: ignore

#237 Handle empty results in reranker
  src/vectorcode/subcommands/query/reranker/base.py
  tests/subcommands/query/test_reranker.py
Labels: bug, fix

#238 Add `deduplicate` parameter to query tool
  lua/vectorcode/integrations/codecompanion/query_tool.lua
Labels: enhancement, feature

#244 Support loading `.gitignore` from nested repo/submodules
  doc/VectorCode-cli.txt
  docs/cli.md
  src/vectorcode/cli_utils.py
  src/vectorcode/subcommands/vectorise.py
  tests/subcommands/test_vectorise.py
  tests/test_cli_utils.py
Labels: enhancement, feature

#245 Update tool descriptions for better loading time
  lua/vectorcode/integrations/codecompanion/ls_tool.lua
  lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
Labels: enhancement, feature

#249 Pin tree-sitter version for linux-arm
  pyproject.toml
Labels: bug, fix

#250 missing comma in docs
  docs/neovim.md
Labels: ignore

#248 Documentation refactor
  .github/workflows/panvimdoc.yml
  README.md
  doc/VectorCode-API.txt
  doc/VectorCode-cli.txt
  doc/VectorCode.txt
  docs/cli.md
  docs/neovim/README.md
  docs/neovim/api_references.md
  lua/vectorcode/types.lua
Labels: documentation

#255 Quote square brackets
  docs/cli.md
Labels: ignore

#258 Enable panvimdoc on PRs
  .github/workflows/panvimdoc.yml
Labels: ignore

#261 Allow `py-tree-sitter>0.25.0`
  pyproject.toml
Labels: ignore
