Repository Davidyz/VectorCode, pull requests merged in 2025-05, with the labels that each got.

#107 feat(cli): Change LSP notification to include project root
  src/vectorcode/lsp_main.py
Labels: feature

#108 fix(nvim): fix job management in cmd runner.
  lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
  lua/vectorcode/jobrunner/cmd.lua
Labels: bug, fix

#117 feat(cli): accept json5 config.
  docs/cli.md
  pyproject.toml
  src/vectorcode/cli_utils.py
  src/vectorcode/lsp_main.py
  src/vectorcode/mcp_main.py
  tests/test_cli_utils.py
  tests/test_lsp.py
Labels: enhancement, feature

#120 fix(cli): preserve spaces and newlines in treesitter chunking.
  src/vectorcode/chunking.py
  tests/test_chunking.py
Labels: bug, fix

#125 fix(nvim): normalise project_root before tool execution.
  lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
  lua/vectorcode/integrations/codecompanion/legacy_tool.lua
Labels: bug, fix

#116 docs: updated documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/cli.md
Labels: documentation

#129 feat(nvim): tuned system prompt and added project_root to the tool output.
  lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
  lua/vectorcode/integrations/codecompanion/legacy_tool.lua
Labels: bug, fix

#135 fix(nvim): fix codecompanion tool error handling.
  lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
  lua/vectorcode/integrations/codecompanion/legacy_tool.lua
Labels: bug, fix

#143 refactor(cli): use `db_url` to replace `host` and `port`.
  docs/cli.md
  src/vectorcode/cli_utils.py
  src/vectorcode/common.py
  src/vectorcode/main.py
  tests/subcommands/test_vectorise.py
  tests/test_cli_utils.py
  tests/test_common.py
Labels: enhancement, feature

#141 fix(nvim): correct the tool schema and make all fields required. Fix #133.
  lua/vectorcode/integrations/codecompanion/func_calling_tool.lua
Labels: bug, fix

#154 fix(cli): make sure `db_url` is updated after starting bundled chroma. Fix #153
  src/vectorcode/common.py
  tests/test_common.py
Labels: bug, fix

#156 fix(cli): use `db_url` for lsp
  src/vectorcode/lsp_main.py
Labels: bug, fix

#155 refactor(nvim): refactor more APIs to use `jobrunner`.
  lua/vectorcode/init.lua
  lua/vectorcode/jobrunner/cmd.lua
Labels: enhancement

#138 feat(cli) Fallback to primary language name when tree_sitter_language_pack won't find a parser for 'hybrid' lexer language names (like 'javascript+genshitext')
  docs/cli.md
  src/vectorcode/chunking.py
  src/vectorcode/cli_utils.py
  tests/test_chunking.py
Labels: enhancement, feature

#157 Static analysis using basedpyright.
  .github/workflows/test_and_cov.yml
  docs/CONTRIBUTING.md
  pyproject.toml
  src/vectorcode/chunking.py
  src/vectorcode/cli_utils.py
  src/vectorcode/common.py
  src/vectorcode/subcommands/ls.py
  src/vectorcode/subcommands/query/__init__.py
  src/vectorcode/subcommands/query/reranker/naive.py
  src/vectorcode/subcommands/vectorise.py
Labels: enhancement

#161 feat(cli): set the default `hnsw:M` value to 64
  docs/cli.md
  src/vectorcode/common.py
  tests/test_common.py
Labels: enhancement, feature
