Repository Davidyz/VectorCode, pull requests merged in 2025-08, with the labels that each got.

#262 Remove outdated API in codecompanion.nvim extension
  lua/vectorcode/integrations/codecompanion/files_ls_tool.lua
  lua/vectorcode/integrations/codecompanion/files_rm_tool.lua
  lua/vectorcode/integrations/codecompanion/init.lua
  lua/vectorcode/integrations/codecompanion/ls_tool.lua
  lua/vectorcode/integrations/codecompanion/query_tool.lua
  lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
Labels: ignore

#267 Handle relative paths for codecompanion tools
  lua/vectorcode/integrations/codecompanion/common.lua
  lua/vectorcode/integrations/codecompanion/files_ls_tool.lua
  lua/vectorcode/integrations/codecompanion/ls_tool.lua
  lua/vectorcode/integrations/codecompanion/query_tool.lua
  lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
Labels: bug, fix

#269 Support using LSP workspace folder as default project root for the LSP server.
  .github/workflows/panvimdoc.yml
  doc/VectorCode-cli.txt
  docs/cli.md
  src/vectorcode/lsp_main.py
  tests/test_lsp.py
Labels: enhancement, feature

#271 Implement cProfile-based profiling for performance analysis
  .github/workflows/panvimdoc.yml
  Makefile
  doc/VectorCode-cli.txt
  docs/cli.md
  pyproject.toml
  src/vectorcode/cli_utils.py
  src/vectorcode/debugging.py
  src/vectorcode/main.py
  tests/test_main.py
Labels: enhancement, feature

#275 Relax schema requirements for CodeCompanion tools (closes #273)
  lua/vectorcode/integrations/codecompanion/files_ls_tool.lua
  lua/vectorcode/integrations/codecompanion/files_rm_tool.lua
  lua/vectorcode/integrations/codecompanion/query_tool.lua
  lua/vectorcode/integrations/codecompanion/vectorise_tool.lua
Labels: enhancement, feature

#278 Only allow HTTP adapters for codecompanion result summarisation
  lua/vectorcode/integrations/codecompanion/query_tool.lua
  lua/vectorcode/types.lua
Labels: bug, fix

#281 Fix type annotation for summarisation adapter.
  lua/vectorcode/types.lua
Labels: bug, fix

#280 Implement `QueryResult` type.
  src/vectorcode/chunking.py
  src/vectorcode/mcp_main.py
  src/vectorcode/subcommands/query/__init__.py
  src/vectorcode/subcommands/query/reranker/base.py
  src/vectorcode/subcommands/query/reranker/cross_encoder.py
  src/vectorcode/subcommands/query/reranker/naive.py
  src/vectorcode/subcommands/query/types.py
  src/vectorcode/subcommands/vectorise.py
  tests/subcommands/query/test_query.py
  tests/subcommands/query/test_reranker.py
  tests/subcommands/query/test_types.py
  tests/subcommands/test_chunks.py
  tests/test_mcp.py
Labels: ignore
